import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { compute, template, normalizePath, type Signal, type Normalized } from '../src/fingerprint.js';

interface Vector {
  name: string;
  signal: Signal;
  expected_fp: string;
  normalized: Normalized;
}

const here = dirname(fileURLToPath(import.meta.url));
// DEVBENCH_TESTDATA: the public SDK repo's CI, whose layout differs.
const vectorsPath = resolve(process.env.DEVBENCH_TESTDATA ?? resolve(here, '../../../testdata'), 'fingerprint_vectors.json');
const vectors: Vector[] = JSON.parse(readFileSync(vectorsPath, 'utf8'));

/**
 * The cross-implementation contract (docs/SERVER_SDK_SPEC.md, "Conformance").
 *
 * These vectors are generated by the Go implementation. If this test fails, the
 * client SDK and the server would count the same problem as two distinct
 * problems: triage cost doubles and one issue splits in half with neither half
 * showing its true impact.
 */
test('fingerprint vectors match the Go implementation exactly', () => {
  assert.ok(vectors.length > 0, 'vector file is empty');

  for (const v of vectors) {
    const got = compute(v.signal);
    assert.equal(
      got.fp,
      v.expected_fp,
      `vector ${v.name}: fingerprint mismatch\n  go: ${v.expected_fp}\n  ts: ${got.fp}\n` +
        `  go normalized: ${JSON.stringify(v.normalized)}\n  ts normalized: ${JSON.stringify(got.normalized)}`,
    );
    assert.deepEqual(got.normalized, v.normalized, `vector ${v.name}: normalized form differs`);
  }
});

test('every vector kind is represented', () => {
  const kinds = new Set(vectors.map((v) => v.signal.kind));
  for (const required of ['error', 'silent_failure', 'log_template', 'degradation']) {
    assert.ok(kinds.has(required), `no vector covers kind "${required}"`);
  }
});

// The same guarantee the Go suite asserts, restated here so the TS port cannot
// drift independently. See ARCHITECTURE_PROPOSAL.md risk #1.
test('a cosmetic refactor does not change the fingerprint', () => {
  const before = compute({
    kind: 'error', source: 'client', type: 'TypeError',
    message: "Cannot read property 'email' of undefined",
    frames: [{ function: 'CustomerCtrl.save', file: 'https://app.example.com/assets/js/app.js?v=8f21a', line: 1204 }],
  });

  const after = compute({
    kind: 'error', source: 'client', type: 'TypeError',
    message: "Cannot read property 'email' of undefined",
    frames: [{ function: 'CustomerCtrl.save', file: 'https://app.example.com/assets/js/app.js?v=c93de', line: 1533 }],
  });

  assert.equal(after.fp, before.fp);
});

test('dependency frames are ignored', () => {
  const clean = compute({
    kind: 'error', source: 'client', type: 'TypeError', message: 'boom',
    frames: [{ function: 'save', file: 'assets/js/app.js', line: 1 }],
  });

  const noisy = compute({
    kind: 'error', source: 'client', type: 'TypeError', message: 'boom',
    frames: [
      { function: 'digest', file: '/app/node_modules/angular/angular.js', line: 17000 },
      { function: 'save', file: 'assets/js/app.js', line: 1 },
    ],
  });

  assert.equal(noisy.fp, clean.fp);
});

test('template collapses varying occurrences', () => {
  assert.equal(template('Completed 200 OK in 45ms'), template('Completed 200 OK in 1993ms'));
  assert.equal(template('user 9912 not found'), 'user <num> not found');
  assert.equal(template('email a@b.co taken'), 'email <email> taken');
});

test('normalizePath strips build roots and cache busters', () => {
  assert.equal(normalizePath('/home/dev/src/acme/services/billing/invoice.go'), 'services/billing/invoice.go');
  assert.equal(normalizePath('https://app.example.com/assets/js/main.min.js?v=8f21a'), 'assets/js/main.min.js');
  assert.equal(normalizePath(''), '');
});

test('compute rejects empty signals', () => {
  assert.throws(() => compute({ kind: '', source: 'client', message: 'x' }));
  assert.throws(() => compute({ kind: 'error', source: '', message: 'x' }));
  assert.throws(() => compute({ kind: 'error', source: 'client' }));
});
